version: "3.9"
services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./.caddy_data:/data
      - ./.caddy_config:/config
      - ./caddy/etc/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/etc/tls_auto:/etc/tls_auto
      - ./caddy/etc/tls_custom:/etc/tls_custom
      - ./caddy/etc/tls_cloudflare:/etc/tls_cloudflare
      - ./mail-acme-challenge:/mail-acme-challenge
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - ./conf/caddy.env
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
