version: "3.9"
services:
  caddy:
    build:
      context: ./caddy
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./.caddy_data:/data
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - ./caddy.env
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
    external: true
